### ISSUE TITLE
Inconsistent feature annotation crashes validator

### ISSUE THREAD

**Issue by archaeodav** [archaeodav/felttegn#26]
Error crashes felttegn under geometry validation. Caused by incosistent annotation returining a poly with empty geometry.

Example:
```
565131.977,6241668.218,63.798,1696,-ANLG A71
565129.353,6241669.133,63.834,1697,-ANLG A71.sortmuldetsand
565125.409,6241689.159,63.719,1698,-ANLG A71.sortmuldetsand
565127.582,6241689.875,63.491,1699,-ANLG A71.sortmuldetsand
```
![image](https://user-images.githubusercontent.com/67315670/139409717-5e3e25d9-a2fb-41e7-9bb0-cbc2ae535212.png)

```
2021-10-29T10:46:44     WARNING    Traceback (most recent call last):
              File "C:\Users/au526889/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 266, in run
              digit = Digi([i],kote_file=kote_file)
              File "C:\Users/au526889/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 672, in __init__
              self.feature_builder()
              File "C:\Users/au526889/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 741, in feature_builder
              self.validator(l)
              File "C:\Users/au526889/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 820, in validator
              errors = self.layers[layer]['features'][feat]["geom"].validateGeometry()
             AttributeError: 'NoneType' object has no attribute 'validateGeometry'
```

**Comment by archaeodav** [comment]
Fixed in upcoming release 1.01
