### ISSUE TITLE
MapInfo .tab creation fails

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#34]
2021-12-03T10:09:27     WARNING    Python-fejl : Der opstod en fejl ved udførelse af Python-kode: Se beskedloggen (Python-fejl) for flere detaljer.
2021-12-03T10:09:27     WARNING    Traceback (most recent call last):
              File "C:/Users/pda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 280, in run
              gjson=gjson)
              File "C:/Users/pda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\felt_tegn\felt_tegn.py", line 989, in feat_export
              raise Exception("No output format chosen")
             Exception: No output format chosen

**Comment by archaeodav** [comment]
Partially fixed in upcoming version  1.2- however, output is not loaded in canvas

**Comment by archaeodav** [comment]
Fixed in release 1.2, BUT no style is applied to the output. I'll close this for now unless there's a lot of demand for TAB export
